[project]
name = "yt-downloader-backend"
version = "0.1.0"
description = "Backend component to manage downloading youtube videos"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "hypercorn>=0.17.3",
]
